//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnvironmentProtectEntities : DbContext
    {
        public EnvironmentProtectEntities()
            : base("name=EnvironmentProtectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostCollect> PostCollect { get; set; }
        public virtual DbSet<PostComment> PostComment { get; set; }
        public virtual DbSet<Postlike> Postlike { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Knowledge> Knowledge { get; set; }
        public virtual DbSet<LifeType> LifeType { get; set; }
        public virtual DbSet<Life> Life { get; set; }
    
        public virtual ObjectResult<Proc_AdmLoginByPassword_Result> Proc_AdmLoginByPassword(Nullable<int> admid, string password)
        {
            var admidParameter = admid.HasValue ?
                new ObjectParameter("Admid", admid) :
                new ObjectParameter("Admid", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_AdmLoginByPassword_Result>("Proc_AdmLoginByPassword", admidParameter, passwordParameter);
        }
    }
}
